import { Game, Template, AITemplate } from '../types/types';

// ---------------------------
// DEFAULT GAMES
// ---------------------------
export const GAMES: Game[] = [ {
    id: 'cognipop',
    name: 'CogniPop',
    creator: 'Default game',
    thumbnailUrl: 'https://picsum.photos/seed/cosmic/400/300',
    description: 'An interstellar strategy game of trade and survival. Conquer galaxies!',
    tags: ['#Strategy', '#SciFi'],
    category: 'Play',
    upvotes: 1200,
    downvotes: 150,
    createdAt: new Date('2023-10-20T10:00:00Z'),
  },
  {
    id: 'Game2',
    name: 'Trial game',
    creator: 'Logic Weavers',
    thumbnailUrl: 'https://picsum.photos/seed/maze/400/300',
    description: 'Sharpen your mind with challenging puzzles that bend the laws of physics.',
    tags: ['#Puzzle', '#Productivity'],
    category: 'Skill',
    upvotes: 3400,
    downvotes: 80,
    createdAt: new Date('2023-11-05T14:30:00Z'),
  },
  {
    id: 'game-3',
    name: 'Kingdoms Collide',
    creator: 'Epic Realities',
    thumbnailUrl: 'https://picsum.photos/seed/kingdoms/400/300',
    description: 'Build your empire and lead vast armies in this epic multiplayer RTS.',
    tags: ['#Strategy', '#Multiplayer'],
    category: 'Play',
    upvotes: 5600,
    downvotes: 450,
    createdAt: new Date('2022-05-15T09:00:00Z'),
  },
  {
    id: 'game-4',
    name: 'Focus Flow',
    creator: 'Zen Den',
    thumbnailUrl: 'https://picsum.photos/seed/focus/400/300',
    description: 'A minimalist puzzle game designed to improve concentration and workflow.',
    tags: ['#Productivity', '#Puzzle'],
    category: 'Skill',
    upvotes: 890,
    downvotes: 20,
    createdAt: new Date('2023-12-01T18:00:00Z'),
  },
  {
    id: 'game-5',
    name: 'Galactic Chef',
    creator: 'Saucy Games',
    thumbnailUrl: 'https://picsum.photos/seed/chef/400/300',
    description: 'Cook exotic dishes for alien customers in this frantic cooking simulation.',
    tags: ['#Simulation', '#Casual'],
    category: 'Play',
    upvotes: 2100,
    downvotes: 300,
    createdAt: new Date('2023-08-11T12:00:00Z'),
  },
  {
    id: 'game-6',
    name: 'Rhythm Runner',
    creator: 'Beat Masters',
    thumbnailUrl: 'https://picsum.photos/seed/rhythm/400/300',
    description: 'Dash and jump to the beat in this electrifying action-rhythm game.',
    tags: ['#Music', '#Action'],
    category: 'Play',
    upvotes: 4200,
    downvotes: 250,
    createdAt: new Date('2023-09-25T20:00:00Z'),
  },
  {
    id: 'game-7',
    name: 'Code Quest',
    creator: 'Devs Dungeon',
    thumbnailUrl: 'https://picsum.photos/seed/code/400/300',
    description: 'Learn to code by solving puzzles and battling monsters with real programming logic.',
    tags: ['#Puzzle', '#Productivity', '#Education'],
    category: 'Skill',
    upvotes: 1500,
    downvotes: 50,
    createdAt: new Date('2023-11-30T11:00:00Z'),
  },
  {
    id: 'game-8',
    name: 'Astro Farmer',
    creator: 'Cosmic Crops',
    thumbnailUrl: 'https://picsum.photos/seed/astro/400/300',
    description: 'Grow fantastical plants on alien worlds in this relaxing sci-fi farming sim.',
    tags: ['#Simulation', '#SciFi'],
    category: 'Play',
    upvotes: 750,
    downvotes: 120,
    createdAt: new Date('2023-01-10T15:00:00Z'),
  },
  {
    id: 'cogniquest',
    name: 'CogniQuest',
    creator: 'Default Game',
    thumbnailUrl: 'https://picsum.photos/seed/cogni/400/300',
    description: 'A logic puzzle adventure to sharpen your brain.',
    tags: ['#Puzzle', '#Strategy'],
    category: 'Default',
    upvotes: 0,
    downvotes: 0,
    createdAt: new Date('2023-10-01T10:00:00Z'),
  },
  {
    id: 'astrodash',
    name: 'AstroDash',
    creator: 'Default Game',
    thumbnailUrl: 'https://picsum.photos/seed/astro/400/300',
    description: 'A fun space-themed runner to test reflexes.',
    tags: ['#Action', '#Casual'],
    category: 'Default',
    upvotes: 0,
    downvotes: 0,
    createdAt: new Date('2023-09-15T12:00:00Z'),
  },
  {
    id: 'brainbuilder',
    name: 'BrainBuilder',
    creator: 'Default Game',
    thumbnailUrl: 'https://picsum.photos/seed/brain/400/300',
    description: 'Improve memory and focus with mini challenges.',
    tags: ['#Productivity', '#Puzzle'],
    category: 'Default',
    upvotes: 0,
    downvotes: 0,
    createdAt: new Date('2023-08-20T09:30:00Z'),
  },
  {
    id: 'codeclash',
    name: 'CodeClash',
    creator: 'Default Game',
    thumbnailUrl: 'https://picsum.photos/seed/code/400/300',
    description: 'Battle coding monsters by solving algorithms.',
    tags: ['#Education', '#Programming'],
    category: 'Default',
    upvotes: 0,
    downvotes: 0,
    createdAt: new Date('2023-11-01T14:00:00Z'),
  },
  {
    id: 'planetchef',
    name: 'Planet Chef',
    creator: 'Default Game',
    thumbnailUrl: 'https://picsum.photos/seed/chef/400/300',
    description: 'Cook and serve alien delicacies across galaxies.',
    tags: ['#Simulation', '#Casual'],
    category: 'Default',
    upvotes: 0,
    downvotes: 0,
    createdAt: new Date('2023-07-25T16:30:00Z'),
  },
  {
    id: 'rhythmblast',
    name: 'RhythmBlast',
    creator: 'Default Game',
    thumbnailUrl: 'https://picsum.photos/seed/rhythm/400/300',
    description: 'Jump and dash to the beat in a vibrant world.',
    tags: ['#Music', '#Action'],
    category: 'Default',
    upvotes: 0,
    downvotes: 0,
    createdAt: new Date('2023-09-10T18:45:00Z'),
  },
  {
    id: 'mindmaze',
    name: 'MindMaze',
    creator: 'Default Game',
    thumbnailUrl: 'https://picsum.photos/seed/maze/400/300',
    description: 'Navigate tricky mazes to challenge your logic.',
    tags: ['#Puzzle', '#Strategy'],
    category: 'Default',
    upvotes: 0,
    downvotes: 0,
    createdAt: new Date('2023-06-30T11:00:00Z'),
  },
  {
    id: 'galacticgardens',
    name: 'Galactic Gardens',
    creator: 'Default Game',
    thumbnailUrl: 'https://picsum.photos/seed/galaxy/400/300',
    description: 'Grow exotic plants on alien worlds.',
    tags: ['#Simulation', '#SciFi'],
    category: 'Default',
    upvotes: 0,
    downvotes: 0,
    createdAt: new Date('2023-05-20T10:00:00Z'),
  },
];

// ---------------------------
// DEFAULT TEMPLATES
// ---------------------------
export const TEMPLATES: Template[] = [
  {
    id: 'template-platformer',
    name: 'Platformer Starter',
    description: 'Basic 2D platformer template with physics and collectibles.',
    thumbnailUrl: 'https://picsum.photos/seed/platformer/400/300',
    tags: ['#2D', '#Beginner'],
    category: 'Default',
    createdAt: new Date('2023-09-01T10:00:00Z'),
    usageCount: 0,
    creator: 'User123',
  },
  {
    id: 'template-rpg',
    name: 'RPG Engine Core',
    description: 'Top-down RPG template with inventory and dialogue system.',
    thumbnailUrl: 'https://picsum.photos/seed/rpg/400/300',
    tags: ['#RPG', '#Intermediate'],
    category: 'Default',
    createdAt: new Date('2023-09-15T12:00:00Z'),
    usageCount: 0,
    creator: 'User123',
  },
  {
    id: 'template-vr',
    name: 'VR Interaction Rig',
    description: 'VR template with prebuilt hand-tracking and interactions.',
    thumbnailUrl: 'https://picsum.photos/seed/vr/400/300',
    tags: ['#VR', '#Advanced'],
    category: 'Default',
    createdAt: new Date('2023-10-01T11:30:00Z'),
    usageCount: 0,
    creator: 'User123',
  },
  {
    id: 'template-runner',
    name: 'Endless Runner Kit',
    description: 'Procedurally generated levels with power-ups.',
    thumbnailUrl: 'https://picsum.photos/seed/runner/400/300',
    tags: ['#Mobile', '#Beginner'],
    category: 'Default',
    createdAt: new Date('2023-10-20T14:00:00Z'),
    usageCount: 0,
    creator: 'User123',
  },
  {
    id: 'template-puzzle',
    name: 'Puzzle Challenge',
    description: 'Create engaging logic puzzles with ease.',
    thumbnailUrl: 'https://picsum.photos/seed/puzzle/400/300',
    tags: ['#Puzzle', '#Intermediate'],
    category: 'Default',
    createdAt: new Date('2023-11-05T09:00:00Z'),
    usageCount: 0,
    creator: 'User123',
  },
  {
    id: 'template-sim',
    name: 'Simulation Starter',
    description: 'Build simulation games quickly with core mechanics ready.',
    thumbnailUrl: 'https://picsum.photos/seed/sim/400/300',
    tags: ['#Simulation', '#Beginner'],
    category: 'Default',
    createdAt: new Date('2023-11-20T12:30:00Z'),
    usageCount: 0,
    creator: 'User123',
  },
  {
    id: 'template-action',
    name: 'Action RPG Base',
    description: 'Template for fast-paced action RPGs with combat system.',
    thumbnailUrl: 'https://picsum.photos/seed/action/400/300',
    tags: ['#Action', '#Advanced'],
    category: 'Default',
    createdAt: new Date('2023-12-01T15:00:00Z'),
    usageCount: 0,
    creator: 'User123',
  },
  {
    id: 'template-music',
    name: 'Music Game Core',
    description: 'Rhythm-based template with scoring and combo system.',
    thumbnailUrl: 'https://picsum.photos/seed/music/400/300',
    tags: ['#Music', '#Intermediate'],
    category: 'Default',
    createdAt: new Date('2023-12-10T17:00:00Z'),
    usageCount: 0,
    creator: 'User123',
  },
  {
    id: 'user-template-1',
    name: 'Alien Shooter',
    description: 'Top-down shooter created by a user. Test AI and gameplay logic.',
    thumbnailUrl: 'https://picsum.photos/seed/alien/400/300',
    tags: ['#Action', '#User'],
    category: 'User',
    createdAt: new Date('2023-11-01T10:00:00Z'),
    usageCount: 12,
    creator: 'User123',
  },
  {
    id: 'user-template-2',
    name: 'Mini Golf Madness',
    description: 'Fun user-created mini golf game template.',
    thumbnailUrl: 'https://picsum.photos/seed/golf/400/300',
    tags: ['#Casual', '#User'],
    category: 'User',
    createdAt: new Date('2023-11-05T14:30:00Z'),
    usageCount: 8,
    creator: 'User456',
  },
  {
    id: 'user-template-3',
    name: 'Puzzle Tower',
    description: 'Stack blocks and solve puzzles in this user template.',
    thumbnailUrl: 'https://picsum.photos/seed/tower/400/300',
    tags: ['#Puzzle', '#User'],
    category: 'User',
    createdAt: new Date('2023-11-10T11:00:00Z'),
    usageCount: 19,
    creator: 'User123',
  },
  {
    id: 'user-template-4',
    name: 'Cyber Racer',
    description: 'Fast-paced racing template created by a user.',
    thumbnailUrl: 'https://picsum.photos/seed/racer/400/300',
    tags: ['#Racing', '#User'],
    category: 'User',
    createdAt: new Date('2023-11-15T16:45:00Z'),
    usageCount: 22,
    creator: 'User456',
  },
  {
    id: 'user-template-5',
    name: 'Magic Card Duel',
    description: 'Card battling template by a user with fantasy theme.',
    thumbnailUrl: 'https://picsum.photos/seed/cards/400/300',
    tags: ['#CardGame', '#User'],
    category: 'User',
    createdAt: new Date('2023-11-20T13:00:00Z'),
    usageCount: 15,
    creator: 'User123',
  },
];

// AI Templates for Creator Mode
export const aiTemplates: AITemplate[] = [
  {
    id: "Text Predictor",
    name: "Text Predictor",
    model: "Prediction",
    image: "/images/ai/text-predictor.png",
  },
  {
    id: "Image Classifier",
    name: "Image Classifier",
    model: "Classification",
    image: "/images/ai/image-classifier.png",
  },
  {
    id: "Sentiment Analyzer",
    name: "Sentiment Analyzer",
    model: "Analysis",
    image: "/images/ai/sentiment-analyzer.png",
  },
  {
    id: "Music Generator",
    name: "Music Generator",
    model: "Generation",
    image: "/images/ai/music-generator.png",
  },
  {
    id: "Chat Simulator",
    name: "Chat Simulator",
    model: "Conversation",
    image: "/images/ai/chat-simulator.png",
  },
  {
    id: "Text Predictor",
    name: "Text Predictor",
    model: "Prediction",
    image: "/images/ai/text-predictor.png",
  },
  {
    id: "Image Classifier",
    name: "Image Classifier",
    model: "Classification",
    image: "/images/ai/image-classifier.png",
  },
  {
    id: "Sentiment Analyzer",
    name: "Sentiment Analyzer",
    model: "Analysis",
    image: "/images/ai/sentiment-analyzer.png",
  },
  {
    id: "Music Generator",
    name: "Music Generator",
    model: "Generation",
    image: "/images/ai/music-generator.png",
  },
  {
    id: "Chat Simulator",
    name: "Chat Simulator",
    model: "Conversation",
    image: "/images/ai/chat-simulator.png",
  },
];


// Available tags for the search filter dropdown.
export const TAGS = ['#Puzzle', '#Strategy', '#Productivity', '#SciFi', '#Multiplayer', '#Simulation', '#Casual', '#Action', '#Music', '#Education'];

// Total upvotes a user can give.
export const TOTAL_VOTE_QUOTA = 50;

// Total skill games a user can play per month.
export const TOTAL_SKILL_GAMES_QUOTA = 2;